
titulo_pelicula = input('Cual es el nombre de la pelicula?: ')
director_pelicula = input('Cual es el nombre del director de la pelicula?: ')
ano_pelicula = input('Cual es el año de lanzamiento de la pelicula?: ')
genero_pelicula = input('Cual es el genero de la pelicula?: ')
duracion_pelicula = float(input('Cual es la duracion de la pelicula?: '))
premios_pelicula = bool(input('Tiene premios(True o False): '))

print('Tu pelicula favorita es:')
print('Titulo:', titulo_pelicula)
print('Director:', director_pelicula)
print('Año de lanzamiento:', ano_pelicula)
print('Genero:', genero_pelicula)
print('Duracion:', duracion_pelicula )
print('Premios:', premios_pelicula)

titulo_pelicula = input('What is the name of the movie?: ')
director_pelicula = input('What is the name of the director of the film?: ')
ano_pelicula = int(input('What is the year of release of the movie?: '))
genero_pelicula = input('What is the genre of the movie?: ')
duracion_pelicula = float(input('What is the length of the movie?: '))
premios_pelicula = bool(input('It has awards(True o False?: '))

print('Your favorite movie is:')
print('Title:', titulo_pelicula)
print('Director:', director_pelicula)
print('Year of release:', ano_pelicula)
print('Genre:', genero_pelicula)
print('Duration:', duracion_pelicula )
print('Awards:', premios_pelicula)