titulo = input('Cual es el titulo de tu cancion favorita?: ')
artista = input('Cual es el nombre del artista?: ')
album = input('Cual es el nombre del album?: ')
ano = int(input('Cual es el año de salida de tu cancion favorita?: '))
duracion = int(input('Cual es la duracion en segundos de tu cancion favorita?: '))
video = bool(input('Tiene videoclip(TRUE o FALSE?: '))

print('Tu cancion favorita es: ')
print('El titulo:', titulo)
print('El artista:', artista)
print('El album:', album)
print('El año de salida:', ano)
print('La duracion:', duracion)
print('Tiene videoclip:', video)

titulo = input('Cual es el titulo de tu cancion menos favorita?: ')
artista = input('Cual es el nombre del artista de tu cancion menos favorita?: ')
album = input('Cual es el nombre del album de tu cancion menos favorita?: ')
ano = int(input('Cual es el año de salida de tu cancion menos favorita?: '))
duracion = int(input('Cual es la duracion en segundos de tu cancion menos favorita ?: '))
video = bool(input('Tiene videoclip(TRUE o FALSE?: '))

print('Tu cancion menos favorita es: ')
print('El titulo:', titulo)
print('El artista:', artista)
print('El album:', album)
print('El año de salida:', ano)
print('La duracion:', duracion)
print('Tiene videoclip:', video)
